// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// App controllers
import AppController from "./app_controller"
application.register("app", AppController)

import ResourceController from "./resource_controller"
application.register("resource", ResourceController)

import NumberInputController from "./number_input_controller"
application.register("number-input", NumberInputController)

import SlimSelectController from "./slim_select_controller"
application.register("slim-select", SlimSelectController)

// 3rd party controllers
import RailsNestedForm from '@stimulus-components/rails-nested-form'
application.register("nested-form", RailsNestedForm)

import Notification from "@stimulus-components/notification"
application.register("notification", Notification)

import AutoSubmit from "@stimulus-components/auto-submit"
application.register("auto-submit", AutoSubmit)

import { Autocomplete } from "stimulus-autocomplete"
// import Autocomplete from "./autocomplete_controller"
application.register("autocomplete", Autocomplete)

// Ruby UI controllers
import RubyUi__AccordionController from "./ruby_ui/accordion_controller"
application.register("ruby-ui--accordion", RubyUi__AccordionController)

import RubyUi__CalendarController from "./ruby_ui/calendar_controller"
application.register("ruby-ui--calendar", RubyUi__CalendarController)

import RubyUi__CalendarInputController from "./ruby_ui/calendar_input_controller"
application.register("ruby-ui--calendar-input", RubyUi__CalendarInputController)

import RubyUi__CheckboxGroupController from "./ruby_ui/checkbox_group_controller"
application.register("ruby-ui--checkbox-group", RubyUi__CheckboxGroupController)

import RubyUi__ComboboxController from "./ruby_ui/combobox_controller"
application.register("ruby-ui--combobox", RubyUi__ComboboxController)

import RubyUi__DialogController from "./ruby_ui/dialog_controller"
application.register("ruby-ui--dialog", RubyUi__DialogController)

import RubyUi__FormFieldController from "./ruby_ui/form_field_controller"
application.register("ruby-ui--form-field", RubyUi__FormFieldController)

import RubyUi__MaskedInputController from "./ruby_ui/masked_input_controller"
application.register("ruby-ui--masked-input", RubyUi__MaskedInputController)

import RubyUi__PopoverController from "./ruby_ui/popover_controller"
application.register("ruby-ui--popover", RubyUi__PopoverController)

import RubyUi__SelectController from "./ruby_ui/select_controller"
application.register("ruby-ui--select", RubyUi__SelectController)

import RubyUi__SelectItemController from "./ruby_ui/select_item_controller"
application.register("ruby-ui--select-item", RubyUi__SelectItemController)

import RubyUi__ThemeToggleController from "./ruby_ui/theme_toggle_controller"
application.register("ruby-ui--theme-toggle", RubyUi__ThemeToggleController)

import RubyUi__TooltipController from "./ruby_ui/tooltip_controller"
application.register("ruby-ui--tooltip", RubyUi__TooltipController)

// Page controllers
import AssetSettingController from "./pages/asset_setting_controller"
application.register("page--asset-setting", AssetSettingController)

import BranchController from "./pages/branch_controller"
application.register("page--branch", BranchController)

// Shared controllers
import ContractController from "./shared/contract_controller"
application.register("shared--contract", ContractController)

import CustomerController from "./shared/customer_controller"
application.register("shared--customer", CustomerController)
