cache:
  current_tenant: "tenant::user::%{user_id}"
max_number_of_file_uploads: 4
max_contract_file_size: 10
max_customer_file_size: 10
remove_customer_file_base_url: "/customers/files/:ID"
remove_contract_file_base_url: "/contracts/files/:ID"
transaction_categories:
  - code: ""
    name: "Tất cả loại hình"
  - code: "pawn"
    name: "Cầm đồ"
  - code: "credit"
    name: "Tín Chấp"
  - code: "installment"
    name: "Trả Góp"
  - code: "capital"
    name: "Nguồn vốn"
  - code: "income"
    name: "Thu hoạt động"
  - code: "expense"
    name: "Chi hoạt động"
  - code: "opening_balance"
    name: "Nhập quỹ tiền đầu ngày"

activity_keys:
  cash_control:
    deposit: "activity.cash_control.deposit"
    update_opening_balance: "activity.cash_control.update_opening_balance"
  contract:
    create: "activity.contract.create"
    update: "activity.contract.update"
    close: "activity.contract.close"
    outstanding_interest: "activity.contract.outstanding_interest"
    debt_repayment: "activity.contract.debt_repayment"
    extend: "activity.contract.extend"
    additional_loan:
      create: "activity.additional_loan.create"
      cancel: "activity.additional_loan.cancel"
    contract_interest_payment:
      paid: "activity.contract_interest_payment.paid"
      cancel: "activity.contract_interest_payment.cancel"
    reduce_principal:
      create: "activity.reduce_principal.create"
      cancel: "activity.reduce_principal.cancel"